# Generated by Django 3.1.7 on 2021-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20210406_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_link',
            field=models.CharField(default='/images/default_image.jpg', max_length=255),
        ),
    ]
