# Generated by Django 3.1.7 on 2021-04-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_post_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_link',
        ),
    ]
