# Generated by Django 3.1.7 on 2021-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20210413_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default='a', null=True, upload_to='images/'),
        ),
    ]
