# Generated by Django 3.1.7 on 2021-04-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20210413_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
